// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'BeliefSlider': typeof import("../../components/BeliefSlider.vue")['default'],
    'Footer': typeof import("../../components/Footer.vue")['default'],
    'Header': typeof import("../../components/Header.vue")['default'],
    'MainCard': typeof import("../../components/MainCard.vue")['default'],
    'MainTile': typeof import("../../components/MainTile.vue")['default'],
    'NavigationBar': typeof import("../../components/NavigationBar.vue")['default'],
    'NavigationDrawer': typeof import("../../components/NavigationDrawer.vue")['default'],
    'Sermon': typeof import("../../components/Sermon.vue")['default'],
    'SermonSlider': typeof import("../../components/SermonSlider.vue")['default'],
    'SvgIcon': typeof import("../../components/SvgIcon.vue")['default'],
    'Video': typeof import("../../components/Video.vue")['default'],
    'VisionSlider': typeof import("../../components/VisionSlider.vue")['default'],
    'Watch': typeof import("../../components/Watch.vue")['default'],
    'SeriesSlider': typeof import("../../components/seriesSlider.vue")['default'],
    'LayoutUtilsInfoComponent': typeof import("../../components/layoutUtils/InfoComponent.vue")['default'],
    'LayoutUtilsThreeCol': typeof import("../../components/layoutUtils/threeCol.vue")['default'],
    'SidemenuSideMenu': typeof import("../../components/sidemenu/SideMenu.vue")['default'],
    'SidemenuSideMenuLink': typeof import("../../components/sidemenu/SideMenuLink.vue")['default'],
    'SidemenuSideMenuTile': typeof import("../../components/sidemenu/SideMenuTile.vue")['default'],
    'UiMediaScroller': typeof import("../../components/ui/mediaScroller.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
  }
}
export {}
